add_executable(freegag
  "application.cpp"
  "application.h"
  "application_types.h"
  "audio.cpp"
  "audio.h"
  "audio_types.h"
  "cdf_archive.cpp"
  "display_host.cpp"
  "display_host.h"
  "display_scene.cpp"
  "display_scene.h"
  "display_types.h"
  "extra/save_load.cpp"
  "extra/save_load.h"
  "extra/save_load_bg_patch.h"
  "extra/synthesized_resource.cpp"
  "extra/synthesized_resource.h"
  "game_host.cpp"
  "game_host.h"
  "host_events.cpp"
  "host_events.h"
  "main.cpp"
  "media.cpp"
  "media.h"
  "media_types.h"
  "pcm_format.h"
  "portable_path.h"
  "resource.cpp"
  "resource.h"
  "resource_types.h"
  "runtime.cpp"
  "runtime.h"
  "runtime_internal.h"
  "runtime_model.cpp"
  "runtime_model.h"
  "runtime_clock.cpp"
  "runtime_clock.h"
  "runtime_tree.cpp"
  "runtime_tree.h"
  "runtime_tree_types.h"
  "runtime_types.h"
  "script.cpp"
  "script.h"
  "script_types.h"
  "shared_binary_file.cpp"
  "shared_binary_file.h"
  "startup.cpp"
  "startup.h"
  "text.cpp"
  "text.h"
  "text_types.h"
)
target_include_directories(freegag PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(freegag PRIVATE
  xtet
  SDL3::SDL3-static
  ZLIB::ZLIBSTATIC
)

add_subdirectory("xtet")
